---
area/skills:
  - changed-files:
      - any-glob-to-any-file:
          - "*/SKILL.md"
          - "*/references/**/*"

area/docs:
  - changed-files:
      - any-glob-to-any-file: "README.md"
      - any-glob-to-any-file: "CONTRIBUTING.md"

area/github:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"

area/pre-commit:
  - changed-files:
      - any-glob-to-any-file: .pre-commit-config.yaml
      - any-glob-to-any-file: .hooks/**/*
